const primaryOrange = "#ff582d",
    primaryPink = "#fd0d8b",
    primaryCyan = "#76defe",
    primaryPeach = "#ff6a6f",
    primaryWhite = "#ffffff",
    pureBlack = "#000000",
    primaryPurpleLight = "#b17dfe",
    primaryPurpleDark = "#731ae8",
    primaryBlackLight = "#393939",
    primaryBlackDark = "#2e2e2e",
    secondaryGray = "#d7d7d7",
    secondaryDarkGray = "#676767",
    secondaryRed = "#eb394f",
    blackDeepDark = "#2a2a2a",
    // for graphs
    lightBlue = "#88c3fc",
    mediumBlue = "#96aafe",
    magenta = "#a394fe",
    secondaryCyan = "#29cdff",
    secondaryPeach = "#ffc092",
    lightGreen = "#2fffb8",
    pink = "#fe96fd",
    lime = "#9effde",
    /* red */
    palette1Dark = "#fe7774",
    palette1Light = "#ffbf95",
    /* purple */
    palette2Dark = "#9369fe",
    /* green */
    palette3Light = "#61e6b1",
    palette3Dark = "#28d5d4",
    /* blue */
    palette4Light = "#6dd9ff",
    palette4Dark = "#3dc2fd",
    palette4Text = "#18c8ff",
    /* blue-purple */
    palette5Light = "#18c8ff",
    palette5Dark = "#6482fe";

export {
    primaryOrange,
    primaryPink,
    primaryCyan,
    primaryPeach,
    primaryWhite,
    pureBlack,
    primaryPurpleLight,
    primaryPurpleDark,
    primaryBlackLight,
    primaryBlackDark,
    secondaryGray,
    secondaryDarkGray,
    secondaryRed,
    blackDeepDark,
    // new colors
    palette1Dark,
    palette1Light,
    palette2Dark,
    palette3Dark,
    palette3Light,
    palette4Dark,
    palette4Light,
    palette4Text,
    palette5Light,
    palette5Dark,
    // for graphs
    lightBlue,
    mediumBlue,
    magenta,
    secondaryCyan,
    secondaryPeach,
    lightGreen,
    pink,
    lime
};

export default {
    primaryOrange,
    primaryPink,
    primaryCyan,
    primaryPeach,
    primaryWhite,
    pureBlack,
    primaryPurpleLight,
    primaryPurpleDark,
    primaryBlackLight,
    primaryBlackDark,
    secondaryGray,
    secondaryDarkGray,
    secondaryRed,
    blackDeepDark,
    // new colors
    palette1Dark,
    palette1Light,
    palette2Dark,
    palette3Dark,
    palette3Light,
    palette4Dark,
    palette4Light,
    palette4Text,
    palette5Light,
    palette5Dark,
    // for graphs
    lightBlue,
    mediumBlue,
    magenta,
    secondaryCyan,
    secondaryPeach,
    lightGreen,
    pink,
    lime
};
